name: Build Test

on: [push, pull_request]

jobs:
  build-debian-testing:
    name: Debian Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dc: [ldc, gdc]

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cd tests/ci/ && docker build -t asgen -f ./Dockerfile .

    - name: Build & Test
      continue-on-error: ${{ matrix.dc == 'gdc' }}
      run: docker run -t -e DC=${{ matrix.dc }} -v `pwd`:/build asgen
           ./tests/ci/build-and-test.sh
